Repository powsybl/powsybl-entsoe, pull requests merged in 2021-05, with the labels that each got.

#3 Add CgmesVoltageLevelsArea (necessary for balances-adjustment from CGMES files describing ENTSO-E area)
  .github/workflows/maven.yml
  entsoe-cgmes-balances-adjustment/pom.xml
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/util/CgmesVoltageLevelsArea.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/util/CgmesVoltageLevelsAreaFactory.java
  entsoe-cgmes-balances-adjustment/src/test/java/com/powsybl/entsoe/cgmes/balances_adjustment/util/CgmesVoltageLevelsAreaTest.java
  entsoe-cgmes-balances-adjustment/src/test/resources/controlArea.xiidm
  pom.xml
Labels: PR: waiting-for-review

#4 CNE module : export SecurityAnalysisResult to XML
  cne/cne-converter/pom.xml
  cne/cne-converter/src/main/java/com/powsybl/cne/converter/CneConstants.java
  cne/cne-converter/src/main/java/com/powsybl/cne/converter/CneExportOptions.java
  cne/cne-converter/src/main/java/com/powsybl/cne/converter/CneExporter.java
  cne/cne-converter/src/main/java/com/powsybl/cne/converter/SecurityAnalysisResultXml.java
  cne/cne-converter/src/main/java/com/powsybl/cne/converter/SecurityAnalysisResultXmlWriterContext.java
  cne/cne-converter/src/test/java/com/powsybl/cne/converter/CneExporterTest.java
  cne/cne-converter/src/test/resources/cne.xml
  cne/cne-converter/src/test/resources/com/powsybl/config/test/config.yml
  cne/cne-converter/src/test/resources/com/powsybl/config/test/filelist.txt
  cne/cne-model/pom.xml
  cne/cne-model/src/main/java/com/powsybl/cne/model/ContingencySeries.java
  cne/cne-model/src/main/java/com/powsybl/cne/model/Measurement.java
  cne/cne-model/src/main/java/com/powsybl/cne/model/MeasurementType.java
  cne/cne-model/src/main/java/com/powsybl/cne/model/MonitoredRegisteredResource.java
  cne/cne-model/src/main/java/com/powsybl/cne/model/RegisteredResource.java
  cne/cne-model/src/main/java/com/powsybl/cne/model/UnitSymbol.java
  cne/cne-model/src/test/java/com/powsybl/cne/converter/CneModelTest.java
  cne/pom.xml
  pom.xml
Labels: PR: ready-to-be-merged

#6 Add data_exchange code & tests
  entsoe-cgmes-balances-adjustment/pom.xml
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/DataExchanges.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/DataExchangesConstants.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/DataExchangesXml.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/StandardBusinessType.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/StandardCodingSchemeType.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/StandardCurveType.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/StandardMessageType.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/StandardProcessType.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/StandardReasonCodeType.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/StandardRoleType.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/StandardStatusType.java
  entsoe-cgmes-balances-adjustment/src/test/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/CgmaExchangesTest.java
  entsoe-cgmes-balances-adjustment/src/test/java/com/powsybl/entsoe/cgmes/balances_adjustment/data_exchange/PevfExchangesTest.java
  entsoe-cgmes-balances-adjustment/src/test/resources/testCGMAMarketDocument_2-0.xml
  entsoe-cgmes-balances-adjustment/src/test/resources/testPEVFMarketDocument_2-0.xml
Labels: PR: waiting-for-review

#8 Add fictitious Area code
  entsoe-cgmes-balances-adjustment/pom.xml
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/util/CgmesBoundariesArea.java
  entsoe-cgmes-balances-adjustment/src/main/java/com/powsybl/entsoe/cgmes/balances_adjustment/util/CgmesBoundariesAreaFactory.java
  entsoe-cgmes-balances-adjustment/src/test/java/com/powsybl/entsoe/cgmes/balances_adjustment/util/CgmesBoundariesAreaTest.java
Labels: PR: waiting-for-test
