Repository powsybl/powsybl-entsoe, pull requests merged in 2024-10, with the labels that each got.

#165 Xnec provider with powsybl core contingency
  docs/flow_decomposition/flow-decomposition-inputs.md
  flow-decomposition/src/main/java/com/powsybl/flow_decomposition/xnec_provider/XnecProviderByIds.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/FlowDecompositionObserverTest.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/FlowDecompositionWithContingencyTests.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/xnec_provider/XnecProviderByIdsTests.java
Labels: Flow decomposition

#168 Bump powsybl-core to 6.5.0 and openlaodflow to 1.13.0
  balances-adjustment/src/test/java/com/powsybl/balances_adjustment/util/CountryAreaTest.java
  flow-decomposition/src/main/java/com/powsybl/flow_decomposition/FlowDecompositionComputer.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/FlowDecompositionTests.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/LossesCompensationTests.java
  pom.xml
Labels: PR: next-release, PR: waiting-for-review

#164 Integrate boundary fix from core
  docs/flow_decomposition/algorithm-description.md
  flow-decomposition/src/main/java/com/powsybl/flow_decomposition/NetPositionComputer.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/CgmesIntegrationTests.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/FlowDecompositionTests.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/NetPositionTest.java
Labels: PR: next-release, PR: waiting-for-review, bug, Flow decomposition

#167 Remove deprecated isOk() for LF results, force connected component to main
  flow-decomposition/src/main/java/com/powsybl/flow_decomposition/FlowDecompositionComputer.java
  flow-decomposition/src/main/java/com/powsybl/flow_decomposition/FlowDecompositionObserver.java
  flow-decomposition/src/main/java/com/powsybl/flow_decomposition/LoadFlowRunningService.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/FlowDecompositionObserverTest.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/FlowDecompositionTests.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/LoadFlowFallbackTests.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/NodalInjectionTests.java
Labels: PR: ready-to-be-merged

#171 Flow decomposition observers refactoring
  docs/flow_decomposition/flow-decomposition-detailed-results.md
  flow-decomposition/src/main/java/com/powsybl/flow_decomposition/FlowComputerUtils.java
  flow-decomposition/src/main/java/com/powsybl/flow_decomposition/FlowDecompositionComputer.java
  flow-decomposition/src/main/java/com/powsybl/flow_decomposition/FlowDecompositionObserver.java
  flow-decomposition/src/main/java/com/powsybl/flow_decomposition/FlowDecompositionObserverList.java
  flow-decomposition/src/test/java/com/powsybl/flow_decomposition/FlowDecompositionObserverTest.java
Labels: Breaking change, PR: ready-to-be-merged
